'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={page:'home',practice:null,exam:null,stats:JSON.parse(localStorage.getItem('ecgLabStats')||'{"answered":0,"correct":0,"best":0,"mistakes":{}}')};
const titles={home:'Dashboard',study:'Study guide',practice:'Guided practice',exam:'Mock exam',review:'Review mistakes'};
function save(){localStorage.setItem('ecgLabStats',JSON.stringify(state.stats)); updateDashboard();}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function nav(page){state.page=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=titles[page];window.scrollTo({top:0,behavior:'smooth'});if(page==='review')renderReview();}
$$('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>nav(b.dataset.open));$$('[data-start]').forEach(b=>b.onclick=()=>startPractice(b.dataset.start==='practice'?null:5));
$('#quickPractice').onclick=()=>startPractice(5);$('#themeToggle').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('ecgTheme',document.body.classList.contains('light')?'light':'dark');};if(localStorage.getItem('ecgTheme')==='light')document.body.classList.add('light');
function updateDashboard(){const s=state.stats,acc=s.answered?Math.round(s.correct/s.answered*100):null;$('#homeAccuracy').textContent=acc===null?'—':acc+'%';$('#homeAnswered').textContent=s.answered;$('#homeMistakes').textContent=Object.keys(s.mistakes).length;$('#homeBest').textContent=s.best?s.best+'%':'—';$('#sideAnswered').textContent=s.answered+' questions';$('#sideBar').style.width=Math.min(100,s.answered/50*100)+'%';}
function renderStudy(){const groups=['All',...new Set(STUDY_TOPICS.map(x=>x.group))];$('#studyFilters').innerHTML=groups.map((g,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${g}">${g}</button>`).join('');let filter='All';const draw=()=>{const q=$('#studySearch').value.toLowerCase();const rows=STUDY_TOPICS.filter(x=>(filter==='All'||x.group===filter)&&(`${x.title} ${x.summary} ${x.points.join(' ')}`).toLowerCase().includes(q));$('#studyGrid').innerHTML=rows.map((x,i)=>`<article class="study-topic"><button class="study-summary" aria-expanded="false"><span class="topic-index">${String(i+1).padStart(2,'0')}</span><div><small>${x.group} · ${x.kicker}</small><h3>${x.title}</h3><p>${x.summary}</p></div><b>＋</b></button><div class="study-detail"><ul>${x.points.map(p=>`<li>${p}</li>`).join('')}</ul><div class="trap"><strong>Common trap</strong><span>${x.trap}</span></div><button class="text-button" data-topic="${x.group}">Practise this topic →</button></div></article>`).join('')||'<div class="empty">No study topic matches your search.</div>';$$('.study-summary').forEach(b=>b.onclick=()=>{const a=b.parentElement.classList.toggle('open');b.setAttribute('aria-expanded',a);b.querySelector('b').textContent=a?'−':'＋';});$$('[data-topic]').forEach(b=>b.onclick=()=>startPractice(null,b.dataset.topic));};$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;draw();});$('#studySearch').oninput=draw;draw();}
function selectedIndexes(root){return $$('input:checked',root).map(x=>+x.value).sort((a,b)=>a-b);}
function same(a,b){return a.length===b.length&&a.every((x,i)=>x===b[i]);}
function questionCard(q,index,total,mode,answers={},submitted=false){const chosen=answers[q.id]||[];return `<article class="question-shell" data-qid="${q.id}"><div class="question-meta"><span>Question ${index+1} of ${total}</span><span>${q.topic}</span><span>${q.difficulty}</span></div><div class="question-grid"><div class="ecg-panel"><button class="zoom-hint" data-zoom="${q.image}">Open full screen ↗</button><img src="${q.image}" alt="ECG question ${index+1}" loading="eager"></div><div class="question-content"><p class="select-note">Select one or more options</p><h2>${q.prompt}</h2><div class="answer-list">${q.options.map((o,i)=>{const isC=q.correct.includes(i),isS=chosen.includes(i);return `<label class="answer-option ${submitted?(isC?'is-correct':isS?'is-wrong':''):''}"><input type="checkbox" value="${i}" ${isS?'checked':''} ${submitted?'disabled':''}><span class="box">${String.fromCharCode(65+i)}</span><span>${o}</span>${submitted&&isC?'<b>✓</b>':submitted&&isS?'<b>×</b>':''}</label>`}).join('')}</div></div></div></article>`;}
function startPractice(limit=null,topic=null){let pool=QUESTION_BANK.filter(q=>!topic||q.topic.includes(topic)||topic==='Rhythm'&&q.topic.toLowerCase().includes('rhythm'));pool=shuffle(pool).slice(0,limit||pool.length);state.practice={questions:pool,index:0,correct:0,answered:0};nav('practice');renderPractice();}
function renderPractice(){const p=state.practice;if(!p){$('#practiceMount').innerHTML='<div class="empty-state"><h2>Ready for a guided session?</h2><p>You will see the explanation immediately after each answer.</p><button class="button primary" id="startDefault">Start practice</button></div>';$('#startDefault').onclick=()=>startPractice();return;}if(p.index>=p.questions.length){const pct=Math.round(p.correct/p.questions.length*100);$('#practiceMount').innerHTML=resultCard('Practice complete',p.correct,p.questions.length,pct,false);bindResultButtons();return;}const q=p.questions[p.index];$('#practiceMount').innerHTML=`<div class="quiz-top"><div class="progress-line"><i style="width:${p.index/p.questions.length*100}%"></i></div><button class="text-button" id="endSession">End session</button></div>${questionCard(q,p.index,p.questions.length,'practice')}<div id="practiceFeedback"></div><div class="quiz-actions"><button class="button primary" id="checkAnswer">Check answer</button></div>`;bindZoom();$('#endSession').onclick=()=>{state.practice=null;nav('home')};$('#checkAnswer').onclick=()=>{const root=$('.question-shell'),sel=selectedIndexes(root);if(!sel.length)return flash('Choose at least one option.');const ok=same(sel,q.correct);p.answered++;if(ok)p.correct++;state.stats.answered++;if(ok)state.stats.correct++;else state.stats.mistakes[q.id]={selected:sel,date:Date.now()};save();root.outerHTML=questionCard(q,p.index,p.questions.length,'practice',{[q.id]:sel},true);$('#practiceFeedback').innerHTML=explanationBlock(q,ok,sel);$('.quiz-actions').innerHTML='<button class="button primary" id="nextPractice">Next question</button>';bindZoom();$('#nextPractice').onclick=()=>{p.index++;renderPractice();};};}
function explanationBlock(q,ok,selected){return `<section class="explanation ${ok?'good':'bad'}"><div class="explanation-head"><span>${ok?'✓':'!'}</span><div><small>${ok?'CORRECT':'NOT QUITE'}</small><h3>${q.explanation}</h3></div></div><div class="option-review">${q.options.map((o,i)=>`<div><b>${String.fromCharCode(65+i)}</b><p><strong>${o}</strong><span>${q.optionNotes[i]}</span></p></div>`).join('')}</div><div class="exam-tip"><b>Exam tip</b><span>${q.tip}</span></div></section>`;}
$('#examForm').onsubmit=e=>{e.preventDefault();const count=+$ ('#examCount').value,time=+$ ('#examTime').value,diff=$('#examDifficulty').value;let pool=diff==='all'?QUESTION_BANK:QUESTION_BANK.filter(q=>q.difficulty===diff);pool=shuffle(pool).slice(0,Math.min(count,pool.length));state.exam={questions:pool,index:0,answers:{},remaining:time*60,timer:null,started:Date.now()};$('#examSetup').style.display='none';renderExam();if(time){state.exam.timer=setInterval(()=>{state.exam.remaining--;updateTimer();if(state.exam.remaining<=0)finishExam();},1000);}};
function renderExam(){const e=state.exam;if(!e)return;const q=e.questions[e.index];$('#examMount').innerHTML=`<div class="exam-bar"><div><strong id="examTimer">${formatTime(e.remaining)}</strong><span>${e.remaining?'remaining':'untimed'}</span></div><div class="exam-dots">${e.questions.map((x,i)=>`<button class="${i===e.index?'active':''} ${e.answers[x.id]?.length?'answered':''}" data-jump="${i}">${i+1}</button>`).join('')}</div><button class="button ghost" id="submitExam">Submit exam</button></div>${questionCard(q,e.index,e.questions.length,'exam',e.answers,false)}<div class="quiz-actions split"><button class="button secondary" id="prevExam" ${e.index===0?'disabled':''}>Previous</button><button class="button primary" id="nextExam">${e.index===e.questions.length-1?'Review & submit':'Save & next'}</button></div>`;bindZoom();const shell=$('.question-shell');$$('input',shell).forEach(x=>x.onchange=()=>e.answers[q.id]=selectedIndexes(shell));$$('[data-jump]').forEach(b=>b.onclick=()=>{e.answers[q.id]=selectedIndexes(shell);e.index=+b.dataset.jump;renderExam();});$('#prevExam').onclick=()=>{e.answers[q.id]=selectedIndexes(shell);e.index--;renderExam();};$('#nextExam').onclick=()=>{e.answers[q.id]=selectedIndexes(shell);if(e.index===e.questions.length-1)showSubmitDialog();else{e.index++;renderExam();}};$('#submitExam').onclick=showSubmitDialog;}
function updateTimer(){const el=$('#examTimer');if(el)el.textContent=formatTime(state.exam.remaining);}function formatTime(s){if(!s)return '∞';return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function showSubmitDialog(){const e=state.exam,done=Object.values(e.answers).filter(x=>x.length).length;if(confirm(`${done} of ${e.questions.length} questions answered. Submit now?`))finishExam();}
function finishExam(){const e=state.exam;if(!e)return;clearInterval(e.timer);let score=0;e.questions.forEach(q=>{const sel=e.answers[q.id]||[],ok=same(sel,q.correct);state.stats.answered++;if(ok){score++;state.stats.correct++;}else state.stats.mistakes[q.id]={selected:sel,date:Date.now()};});const pct=Math.round(score/e.questions.length*100);state.stats.best=Math.max(state.stats.best,pct);save();$('#examMount').innerHTML=resultCard('Mock exam complete',score,e.questions.length,pct,true)+`<div class="exam-review">${e.questions.map((q,i)=>`<details><summary><span>${same(e.answers[q.id]||[],q.correct)?'✓':'×'}</span>Question ${i+1} · ${q.topic}<b>${same(e.answers[q.id]||[],q.correct)?'Correct':'Review'}</b></summary>${questionCard(q,i,e.questions.length,'review',e.answers,true)}${explanationBlock(q,same(e.answers[q.id]||[],q.correct),e.answers[q.id]||[])}</details>`).join('')}</div>`;$('#examSetup').style.display='';$('#examSetup').style.display='none';bindResultButtons();bindZoom();state.exam=null;}
function resultCard(title,score,total,pct,exam){return `<div class="result-card"><p class="eyebrow">SESSION SUMMARY</p><h2>${title}</h2><div class="score-ring" style="--score:${pct}"><strong>${pct}%</strong><span>${score} / ${total}</span></div><p>${pct>=85?'Strong performance. Keep reviewing the reasoning behind each choice.':pct>=70?'Good foundation. Review the missed patterns before your next attempt.':'Use the study guide, then repeat the missed questions.'}</p><div><button class="button primary" id="resultRestart">${exam?'New exam':'Practise again'}</button><button class="button secondary" id="resultReview">Review mistakes</button></div></div>`;}
function bindResultButtons(){if($('#resultRestart'))$('#resultRestart').onclick=()=>state.page==='exam'?nav('exam'):startPractice();if($('#resultReview'))$('#resultReview').onclick=()=>nav('review');}
function renderReview(){const entries=Object.entries(state.stats.mistakes);if(!entries.length){$('#reviewMount').innerHTML='<div class="empty-state"><span>✓</span><h2>No saved mistakes</h2><p>Incorrect practice and exam questions will appear here with full explanations.</p><button class="button primary" id="reviewStart">Start practice</button></div>';$('#reviewStart').onclick=()=>startPractice();return;}$('#reviewMount').innerHTML=`<div class="review-head"><div><p class="eyebrow">PERSONALISED REVIEW</p><h2>${entries.length} pattern${entries.length===1?'':'s'} to revisit</h2></div><button class="button ghost" id="clearMistakes">Clear list</button></div><div class="review-list">${entries.map(([id,data],i)=>{const q=QUESTION_BANK.find(x=>x.id==id);return q?`<details><summary><span>${i+1}</span><div><small>${q.topic} · ${q.difficulty}</small><strong>${q.prompt}</strong></div><b>Open review</b></summary>${questionCard(q,i,entries.length,'review',{[q.id]:data.selected||[]},true)}${explanationBlock(q,false,data.selected||[])}</details>`:''}).join('')}</div>`;$('#clearMistakes').onclick=()=>{if(confirm('Clear all saved mistakes?')){state.stats.mistakes={};save();renderReview();}};bindZoom();}
function bindZoom(){$$('[data-zoom]').forEach(b=>b.onclick=()=>{$('#modalImage').src=b.dataset.zoom;$('#imageModal').classList.add('open');});}$('#modalClose').onclick=()=>$('#imageModal').classList.remove('open');$('#imageModal').onclick=e=>{if(e.target.id==='imageModal')e.currentTarget.classList.remove('open');};
function flash(msg){let x=$('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x);}x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800);}
renderStudy();updateDashboard();renderPractice();
